src/main/java/domain/Person.java, src/main/java/persistence/Application.java, src/main/java/persistence/sql/ddl/ColumnBuilder.java, src/main/java/persistence/sql/ddl/CreateQueryBuilder.java, src/main/java/persistence/sql/ddl/DropQueryBuilder.java, src/main/java/persistence/sql/ddl/StringConstant.java, src/main/java/persistence/sql/ddl/TableName.java, src/main/java/persistence/sql/ddl/TypeMapper.java, src/test/java/persistence/sql/ddl/ColumnBuilderTest.java, src/test/java/persistence/sql/ddl/CreateQueryBuilderTest.java, src/test/java/persistence/sql/ddl/DropQueryBuilderTest.java, src/test/java/persistence/sql/ddl/TableNameTest.java, src/test/java/persistence/sql/ddl/TypeMapperTest.java, src/test/java/step1/Car.java, src/test/java/step1/PrintView.java, src/test/java/step1/ReflectionTest.java
수강생으로써 경험할 수 있는 모든 컨텐츠를 경험하고 싶어서, Step1 도 병행하였습니다.
가능한 TDD 사이클을 지키며 public 하게 공개된 로직은 테스트가 존재하도록 노력했습니다.
=> Step2: DDL (create 와 drop 쿼리빌더 구현)

README.md, src/main/java/persistence/Application.java, src/main/java/persistence/dialect/Dialect.java, src/main/java/persistence/dialect/H2DbDialect.java, src/main/java/persistence/dialect/MySqlDbDialect.java, src/main/java/persistence/dialect/collection/Dialects.java, src/main/java/persistence/dialect/collection/IdGeneratedValueStrategyMap.java, src/main/java/persistence/dialect/type/JavaToH2Type.java, src/main/java/persistence/dialect/type/JavaToMySqlType.java, src/main/java/persistence/entity/Person.java, src/main/java/persistence/sql/Columns.java, src/main/java/persistence/sql/QueryBuilder.java, src/main/java/persistence/sql/ddl/DdlQueryBuilder.java, src/main/java/persistence/sql/ddl/JavaToSqlColumnParser.java, src/main/java/persistence/sql/dml/DmlQueryBuilder.java, src/test/java/persistence/sql/ddl/DdlQueryBuilderTest.java, src/test/java/persistence/sql/ddl/JavaToSqlColumnParserTest.java, src/test/java/persistence/sql/ddl/collection/IdGeneratedValueStrategyMapTest.java, src/test/java/persistence/sql/dml/DmlQueryBuilderTest.java
안녕하세요 성주님.
step3 DML 구현해 보았습니다.
findById 할때 고민되는 부분이 많았어요..
지금은 단순 id 조회이지만.. where 절에 많은 조회 조건이 붙게되면 어떻게 해야할까요?
고민하다가 과제 제출이 늦어질 것 같아서 일단 id 조건만 만족하도록 작업해 보았습니다.
=> Step3 리뷰 요청 드립니다.

src/main/java/jdbc/JdbcTemplate.java, src/main/java/persistence/sql/ddl/Person.java, src/main/java/persistence/sql/dml/DmlGenerator.java, src/test/java/persistence/sql/dml/DatabaseTest.java, src/test/java/persistence/sql/dml/DmlGeneratorTest.java
2단계에서 주신 피드백을 반영하고자 기존 쿼리 빌더를 고도화해보려고 했는데, 
고민이 많아져서 시간이 지연되는 것 같아 우선은 이번 단계 목표인 DDL 생성 기능에 중점을 두고 진행했습니다.
다음 미션들에서도 이번 미션에서 작성한 쿼리 빌더를 계속 들고 갈 것이기 때문에
장기적인 관점에서 미션을 진행하면서 쿼리 빌더를 점진적으로 개선해보도록 하겠습니다.
이번 단계도 잘 부탁드립니다 🙏
=> [🚀 3단계 - DML] 리뷰 요청 드립니다.

src/test/java/persistence/study/StringTest.java
안녕하세요! 이번과정을 듣게된 김병희 입니다.
앞으로 잘부탁드립니다!
StringTest
- 123 이라는 숫자를 문자열로 반환
=> step0 - String 클래스의 학습 테스트

src/test/java/persistance/study/StringTest.java
=> [step0] TDD 실습

src/test/java/persistence/study/StringTest.java
=> StringTest convert 테스트 리뷰요청

src/main/java/persistence/String.java, src/test/java/persistence/StringTest.java
=> Step0 구현되어 PR 요청드립니다.

src/test/java/persistence/StringTest.java
=> first commit

src/test/java/persistence/StringTest.java
- upstream과 관련된 git 과정이 정상적으로 이루어지는지 테스트하는 코드
=> [STEP0] : 초기환경세팅에 관련된 세팅 추가

src/test/java/persistence/StringTest.java
=> feat : test commit

src/main/java/persistence/String.java, src/test/java/persistence/study/StringTest.java
=> [Step0] 0단계 - TDD 실습 제출합니다.

src/test/java/persistence/study/StringTest.java
=> feat: test code 작성

src/test/java/persistence/study/StringTest.java
=> step0: test: add convert int to string test

src/test/java/StringTest.java
=> test: PR 테스트

src/main/java/persistence/study/Car.java, src/main/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
@cndqjacndqja 님과 페어 프로그래밍 한 뒤 몇가지 리팩토링을 추가 했습니다. 감사합니다!
=> [1주차 - Step 1] Reflection PR 입니다.

README.md, src/test/java/persistence/study/Car.java, src/test/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
안녕하세요. 정완님 
1단계 - Reflection 요구사항 구현이 완료되어 PR 요청 드립니다.
앞으로 잘 부탁드립니다. 😄
=> [ 1단계 ] - Reflection  PR 요청 

src/main/java/reflection/Car.java, src/main/java/reflection/PrintView.java, src/test/java/reflection/CarTest.java
=> step1 구현완료되어 리뷰 요청드립니다

src/test/java/persistence/study/Car.java, src/test/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
안녕하세요! 리플렉션 API 테스트코드 작성하여 리뷰요청 드립니다!
오랜만에 넥스트스텝 강의를 수강하게 되어서 설레이네요ㅎㅎ
열심히 따라가면서 유익한 시간 만들어보도록 하겠습니다 감사합니다!
=> step 1-1) 1단계 - Reflection 리뷰요청 드립니다!

src/test/java/persistence/study/Car.java, src/test/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
=> [step1] Reflection 실습

src/test/java/persistance/study/Car.java, src/test/java/persistance/study/PrintView.java, src/test/java/persistance/study/ReflectionTest.java
=> [step1] Reflection

src/main/java/persistence/Application.java, src/main/java/persistence/MyString.java, src/main/java/persistence/study/Car.java, src/main/java/persistence/study/PrintView.java, src/test/java/persistence/MyStringTest.java, src/test/java/persistence/ReflectionTest.java
=> feat: ReflectionTest

src/test/java/persistence/study/Car.java, src/test/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectTest.java
안녕하세요!
ReflectionTest PR 요청입니다.
감사합니다.
=> [Week 1 - Step 1] Reflection PR 요청입니다.

src/test/java/persistence/study/Car.java, src/test/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
안녕하세요 😃 !! 
사실 Reflection 관련해서 처음 사용해보는거나 마찬가지라 많이 헤맸던 것 같아요 😅
하지만 다음 미션을 미리 봤을 때 왜 Reflection을 이용하였는지 납득도 되었고
(아마도?) 이후 미션이 재미있을 것 같단 생각도 들었는데 ㅎ.ㅎ....
이번 PR 잘 부탁 드리겠습니다 ( _ _ ) !!!
=> [1단계] - Reflection Test

src/main/java/persistence/study/Car.java, src/main/java/persistence/study/PrintView.java, src/test/java/persistence/StringTest.java, src/test/java/persistence/study/ReflectionTest.java
=> [Week1-step1] ReflectionTest PR 리뷰 요청드립니다

src/main/java/persistence/study/Car.java, src/main/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
안녕하세요 요한님 step1 미션 제출합니다!
잘 부탁드립니다~ :)
=> [step1]- Reflection Test 미션 제출합니다.

src/test/java/persistence/study/Car.java, src/test/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
안녕하세요~~ Reflection 미션 제출합니다.
제가 평소 테스트 코드를 많이 작성해보지 않아서 처음 써보는 메소드들이 많았습니다.
객체 지향 설계를 참고해보려고 조금이나마 노력했습니다,.,,
요번 미션 동안 잘 부탁 드립니다!! 😃
=> [Step1] 1단계 - Reflection

src/test/java/persistence/study/Car.java, src/test/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
=> [Step1] 🚀 1단계 - Reflection

src/test/java/persistence/study/Car.java, src/test/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
안녕하세요.
step 1 Reflection pr 올립니다
=> 1주차 Step1 Reflection

src/main/java/domain/Person.java, src/main/java/persistence/core/ApplicationPathEntityTargetSourceClassLoader.java, src/main/java/persistence/core/ApplicationPathEntityTargetSourceLoader.java, src/main/java/persistence/core/EntityClassLoader.java, src/main/java/persistence/core/EntityColumn.java, src/main/java/persistence/core/EntityMetadataModel.java, src/main/java/persistence/core/EntityMetadataModelFactory.java, src/main/java/persistence/core/EntityMetadataModels.java, src/main/java/persistence/exception/NotHavePrimaryKeyException.java, src/main/java/persistence/sql/ddl/Dialect.java, src/main/java/persistence/sql/ddl/TableDdlQueryBuilder.java, src/main/java/persistence/sql/ddl/h2/H2Dialect.java, src/main/java/persistence/sql/ddl/h2/H2TableDdlQueryBuilder.java, src/test/java/entityloaderfixture/PersonFixtureEntity.java, src/test/java/entityloaderfixture/StartEntityPath.java, src/test/java/entityloaderfixture/depth/DepthPersonFixtureEntity.java, src/test/java/persistence/core/ApplicationPathEntityTargetSourceLoaderTest.java, src/test/java/persistence/sql/ddl/h2/H2TableDdlQueryBuilderTest.java, src/test/java/reflection/CarTest.java
안녕하세요! 
Step2 구현 완료되어 리뷰 요청드립니다.
잘 만들어보고 싶은 마음에 Entity Class java file들을 찾아서 DDL을 자동으로 생성하는 로직을 만들어야 할까? 라는 의문으로 만들다가 지우기는 아까워서 남겨 두었어요 😅 
라이브러리를 개발하는것이다 보니까 자주 변화하는 애플리케이션 코드와 다르게 추상화를 먼저 적용해볼 수 있을것 같아서 적용해봤습니다.
리뷰 잘부탁드립니다! 🙏🏻
=> Step2 구현완료되어 리뷰 요청 드립니다!

src/main/java/persistence/entity/Person.java, src/main/java/persistence/sql/DbmsQueryBuilder.java, src/main/java/persistence/sql/QueryBuilder.java, src/main/java/persistence/sql/dbms/DbmsStrategy.java, src/main/java/persistence/sql/dbms/mapper/name/NameMapper.java, src/main/java/persistence/sql/dbms/mapper/name/SnakeCaseNameMapper.java, src/main/java/persistence/sql/dbms/mapper/name/UpperSnakeCaseNameMapper.java, src/main/java/persistence/sql/dbms/mapper/type/H2TypeMapper.java, src/main/java/persistence/sql/dbms/mapper/type/TypeMapper.java, src/main/java/persistence/sql/ddl/CreateDDLQueryBuilder.java, src/main/java/persistence/sql/ddl/DropDDLQueryBuilder.java, src/main/java/persistence/sql/entitymetadata/model/EntityColumn.java, src/main/java/persistence/sql/entitymetadata/model/EntityColumns.java, src/main/java/persistence/sql/entitymetadata/model/EntityTable.java, src/main/java/persistence/sql/entitymetadata/model/EntityValidatable.java, src/test/java/persistence/sql/dbms/mapper/name/FakeVeryVeryLongNameEntity.java, src/test/java/persistence/sql/dbms/mapper/name/SnakeCaseNameMapperTest.java, src/test/java/persistence/sql/dbms/mapper/name/UpperSnakeCaseNameMapperTest.java, src/test/java/persistence/sql/dbms/mapper/type/H2TypeMapperTest.java, src/test/java/persistence/sql/ddl/CreateDDLQueryBuilderIntegrationTest.java, src/test/java/persistence/sql/ddl/CreateDDLQueryBuilderTest.java, src/test/java/persistence/sql/ddl/DropDDLQueryBuilderIntegrationTest.java, src/test/java/persistence/sql/ddl/DropDDLQueryBuilderTest.java, src/test/java/persistence/sql/entitymetadata/model/EntityColumnTest.java, src/test/java/persistence/sql/entitymetadata/model/EntityColumnsTest.java, src/test/java/persistence/sql/entitymetadata/model/EntityTableTest.java, src/test/java/persistence/sql/entitymetadata/model/EntityValidatableTest.java, src/test/java/persistence/testutils/H2TableMetaResultRow.java, src/test/java/persistence/testutils/TestQueryExecuteSupport.java
안녕하세요 리뷰어님, 2단계 QueryBuilder DDL (Create, Drop) 구현하여 리뷰 요청드립니다!
다음 Step에서 고민하고 구현해야 할 사항들도 많이 있을것 같아, 당장의 문제를 해결하기 위한 정도의 수준으로 구현을 해보았는데, 피드백 부탁드리겠습니다..!
=> [Step2] 🚀 2단계 - QueryBuilder DDL 구현

src/main/java/jdbc/JdbcTemplate.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/entity/JdbcEntityManager.java, src/main/java/persistence/sql/ddl/builder/ColumnBuilder.java, src/main/java/persistence/sql/ddl/builder/CreateQueryBuilder.java, src/main/java/persistence/sql/dialect/DialectFactory.java, src/main/java/persistence/sql/dml/ColumnValues.java, src/main/java/persistence/sql/dml/DmlQueryGenerator.java, src/main/java/persistence/sql/dml/builder/DeleteQueryBuilder.java, src/main/java/persistence/sql/dml/builder/WhereClauseBuilder.java, src/test/java/persistence/entity/JdbcEntityManagerTest.java, src/test/java/persistence/mock/MockEntity.java, src/test/java/persistence/sql/ddl/builder/ColumnBuilderTest.java, src/test/java/persistence/sql/dialect/DialectFactoryTest.java, src/test/java/persistence/sql/dml/ColumnValuesTest.java, src/test/java/persistence/sql/dml/builder/DeleteQueryBuilderTest.java, src/test/java/persistence/sql/dml/builder/WhereClauseBuilderTest.java
성주님 안녕하세요!
1-4 단계 미션 완료하여 리뷰요청 드립니다😄
EntityManager 의 구현체 이름을 무엇으로 정해야 하나 고민하다가
JdbcTemplate 에 의존하도록 설계되어 있어서 JdbcEntityManager 라고 명명하였는데요!
엔티티 매니저가 데이터베이스와의 연계처리에 대한 책임에 비추어 보았을 때, 이 명명이 괜찮으신지 궁금합니다😃
첫 주차 미션이 제게는 많이 낯설었는데, 성주님께서 잘 이끌어주셔서 따라올 수 있었던 것 같네요😂
살짝 늦은감이 있지만 완주를 목표로 남은 과제들도 열심히 따라가보겠습니다! 감사합니다!
=> Step 1-4) Simple Entity Object 미션 리뷰요청 드립니다!

src/main/java/jdbc/JdbcTemplate.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/entity/SimpleEntityManager.java, src/main/java/persistence/sql/ddl/ColumnOption.java, src/main/java/persistence/sql/ddl/EntityDefinitionBuilder.java, src/main/java/persistence/sql/ddl/EntityMetadata.java, src/main/java/persistence/sql/ddl/FieldMetadataExtractor.java, src/main/java/persistence/sql/ddl/FieldMetadataExtractors.java, src/main/java/persistence/sql/ddl/annotation/ColumnAnnotationHandler.java, src/main/java/persistence/sql/ddl/annotation/GeneratedValueAnnotationHandler.java, src/main/java/persistence/sql/ddl/annotation/IdAnnotationHandler.java, src/main/java/persistence/sql/ddl/scheme/ColumnSchemes.java, src/main/java/persistence/sql/dml/EntityManipulationBuilder.java, src/test/java/persistence/entity/Person.java, src/test/java/persistence/entity/SimpleEntityManagerTest.java, src/test/java/persistence/sql/ddl/EntityDefinitionBuilderTest.java, src/test/java/persistence/sql/dml/EntityManipulationBuilderTest.java
=> 4단계 - Simple Entity Object

src/main/java/domain/Person.java, src/main/java/jdbc/RowMapper.java, src/main/java/persistence/dialect/Dialect.java, src/main/java/persistence/sql/Query.java, src/main/java/persistence/sql/QueryBuilder.java, src/main/java/persistence/sql/ddl/CreateQueryBuilder.java, src/main/java/persistence/sql/ddl/DropQueryBuilder.java, src/main/java/persistence/sql/dml/DeleteQueryBuilder.java, src/main/java/persistence/sql/dml/InsertQueryBuilder.java, src/main/java/persistence/sql/dml/SelectQueryBuilder.java, src/main/java/sources/AnnotationBinder.java, src/main/java/sources/ColumnMetaData.java, src/main/java/sources/MetaData.java, src/main/java/sources/MetadataGeneratorImpl.java, src/test/java/persistence/sql/ddl/DDLTest.java, src/test/java/persistence/sql/dml/DMLTest.java, src/test/java/persistence/sql/dml/GenericRowMapper.java
=> 많이 늦었지만 Step3 리뷰요청드립니다,,

src/main/java/jdbc/PersonRowMapper.java, src/main/java/persistence/entity/EntityManager.java, src/main/java/persistence/entity/EntityManagerImpl.java, src/main/java/persistence/entity/Person.java, src/main/java/persistence/sql/dml/DataManipulationLanguageGenerator.java, src/main/java/persistence/sql/dml/assembler/DataManipulationLanguageAssembler.java, src/main/java/persistence/sql/usecase/GetIdDatabaseFieldUseCase.java, src/main/java/persistence/sql/vo/type/TypeConverter.java, src/test/java/persistence/PersonIntegrationTest.java, src/test/java/persistence/TestUtils.java, src/test/java/persistence/entity/EntityManagerTest.java, src/test/java/persistence/sql/dml/assembler/DataManipulationLanguageAssemblerH2Test.java
안녕하세요 리뷰어님. 1주차 Simple Entity Object PR 올립니다. 
* Delete 의 경우 Object 를 받을 수 있도록 변경했고 Object 의 id 값과 필드를 리플렉션으로 빼내도록 수정했습니다.
* EntityManager 가 JdbcTemplate 을 이용하도록 했습니다.
* spring jdbc template 같은 경우엔 KeyHolder 를 지정할 수 있었던것 같은데 아직 그것까진 구현하지 못해서 Person 에 setId 를 추가했습니다. Id Key 관련해서는 조언해주시면 감사하겠습니다.
=> [step4] 4단계 - Simple Entity Object 리뷰부탁드립니다.

README.md, src/test/java/persistence/study/StringTest.java
=> Step0 - TDD 실습

README.md, src/test/java/persistence/study/StringTest.java
=> 🚀 0단계 - TDD 실습

src/test/java/persistence/study/StringTest.java
=> [step0] 123을 문자열로 리턴하는 테스트를 추가하라

src/test/java/persistence/study/StringTest.java
- convert() 테스트 추가
- 테스트만 통과하도록 테스트 수정
=> step 0 - 테스트 추가

src/test/java/persistence/study/StringTest.java
=> feat: step0

src/test/java/persistence/study/StringTest.java
안녕하세요, 리뷰어님 PR 요청드립니다! 감사합니다 🙇🏻
=> Step0 : String class 학습 테스트

src/test/java/persistence/study/StringTest.java
=> feat : 123 이라는 숫자를 문자열로 반환

src/test/java/persistence/study/StringTest.java
=> test(StringTest): Add test method commit

src/test/java/persistence/study/StringTest.java
=> step 0 - conv() 구현 수정(알림테스트)

src/main/java/persistence/study/Car.java, src/main/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
=> 🚀 1단계 - Reflection

src/main/java/persistence/study/Car.java, src/main/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
=> step 1 요구사항 1,2,3,4,5 구현

build.gradle, src/test/java/persistence/study/Car.java, src/test/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
- 요구사항 1 - 클래스 정보 출력
- 요구사항 2 - test로 시작하는 메소드 실행
- 요구사항 3 - @PrintView 애노테이션 메소드 실행
- 요구사항 4 - private field에 값 할당
- 요구사항 5 - 인자를 가진 생성자의 인스턴스 생성
=> feat: step1 미션 수행

src/test/java/persistence/study/Car.java, src/test/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
안녕하세요 리뷰어님 🙇🏻  만나뵙게되어 반갑습니다!
리뷰 부탁드립니다 😄
=> step1 reflection api 페어프로그래밍

src/test/java/persistence/study/Car.java, src/test/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
=> Step1 - Reflection

README.md, src/main/java/persistence/study/Car.java, src/main/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
안녕하세요 리뷰어님 1단계 요구사항 구현 후 PR 요청 드립니다.
앞으로 잘부탁드립니다😊
=> 🚀1단계-Reflection

README.md, src/main/java/persistence/study/Car.java, src/main/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
김성주 리뷰어님 안녕하세요 ㅎㅎ 
저는 윤주리라고 합니다!
제가 너무 늦었죠?..?
어제 저녁에 술약속이 있어서 기절 당하고 이제 제출하게 되었어요 ㅎㅎ ㅠㅠ 
아직도 제정신이 아니네요.. 술을 한 달에 한 번 마셔서 앞으로 안늦을거에요..
`1차 리뷰신청은 쉽게 생각해서 보내기` 를 말씀주셔서 아래 순서로 작성 후 PR 보냅니다.
1. 요구사항 분석 후 작성 ([README](https://github.com/next-step/jpa-query-builder/compare/jurlring...jurlring:jpa-query-builder:step1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5))
2. 요구사항 기반으로 테스트 작성
아참 제가 🚀 1단계 - Reflection에서 오타를 발견했어용 ㅎㅎ 
앞으로 잘 부탁드립니다!
=> [Step1 - Reflection] 윤주리 미션 제출합니다.

README.md, src/main/java/persistence/Application.java, src/main/java/persistence/entity/Person.java, src/main/java/persistence/entity/Person1.java, src/main/java/persistence/entity/Person2.java, src/main/java/persistence/sql/ddl/DDLQueryBuilder.java, src/test/java/persistence/sql/ddl/DDLQueryBuilderTest.java, src/test/java/persistence/study/ReflectionTest.java
안녕하세요 리뷰어님! 
step2 미션 PR올립니당! 
첫 PR은 조금 가벼운 마음으로..^^ ddl 쿼리 생성 위주로 작성했는데 아마 의견 많이 주실 것 같습니당
잘 부탁드립니다~!
step1에 코멘트 주셨던 assertAll을 적용해두었습니다. README 요구사항 빼먹었었네요🥲
=> Step2 - QueryBuilder DDL

src/test/java/persistence/study/Car.java, src/test/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
=> [Step1] ReflectionTest

src/main/java/persistence/study/Car.java, src/main/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java, src/test/java/persistence/study/StringTest.java
=> 1단계 - Reflection

src/test/java/persistence/study/Car.java, src/test/java/persistence/study/PrintView.java, src/test/java/persistence/study/ReflectionTest.java
안녕하세요 리뷰어님!
step1 리뷰 요청드립니다.
감사합니다.
=> Step1 : Reflection

README.md, src/main/java/persistence/sql/ddl/DDLHelper.java, src/main/java/persistence/sql/ddl/Person.java, src/main/java/persistence/sql/ddl/model/Column.java, src/main/java/persistence/sql/ddl/model/Condition.java, src/main/java/persistence/sql/ddl/model/PKColumn.java, src/main/java/persistence/sql/ddl/model/Type.java, src/test/java/persistence/sql/ddl/DDLHelperTest.java
Step2 PR 입니다!
리뷰 부탁드립니다.
감사합니다.🙏
=> Step2 PR 입니다.

README.md, src/main/java/domain/Person.java, src/main/java/persistence/DefaultEntityManager.java, src/main/java/persistence/EntityManager.java, src/main/java/persistence/sql/ddl/column/Columns.java, src/main/java/persistence/sql/ddl/table/Table.java, src/main/java/persistence/sql/dml/DMLGenerator.java, src/main/java/persistence/sql/dml/clause/ValueClause.java, src/main/java/persistence/sql/dml/clause/WhereClause.java, src/test/java/persistence/DefaultEntityManagerTest.java, src/test/java/persistence/NotEntity.java, src/test/java/persistence/sql/dml/clause/ValueClauseTest.java, src/test/java/persistence/sql/dml/clause/WhereClauseTest.java
성주님 안녕하세요 ㅠ.ㅠ 성주님께 보내는 마지막 PR이네요..ㅠ.ㅠ
지난 미션에 리뷰 주셨던 부분에 [궁금한 점](https://github.com/next-step/jpa-query-builder/pull/216#discussion_r1511344097)을 댓글로 달았는데 확인 부탁드립니다!
마지막도 잘 부탁드려용 :)
=> [Step4 - Simple Entity Object] 윤주리 미션 제출합니다.
